### PR TITLE
add new props to control header and content gesture

### PR DESCRIPTION
**Pull request by ahmaddehnavi**
add new props to control header and content gesture

### CODE REVIEW

**Comment by tensfeld** [comment]
This is related to #74: Disable enabledGestureInteraction only for content
@franjorub

**Comment by franjorub** [comment]
@tensfeld amazing, thank you !

**Comment by pixoudev** [comment]
Hi, perfect. 
I need this feature too. 
But how can I use it, because it's not release yet ?

**Comment by pixoudev** [comment]
I add an issue here because is related with new porps : enabledGestureContentInteraction.

When we use scrool view inside content, thanks enabledGestureContentInteraction, the content size is not resizing when we move the bottomsheet. So, when bottomsheet take all screen we can reach bottom of scrollview but when it is on middle the end of bottomsheet is never reachable.  :)

**Pull request merged**
